baseURL             = ""
languageCode        = "en-us"
title               = "Qtile"
theme               = "qtail"

sectionPagesMenu    = "main"


[permalinks]
    posts           = "posts/:month/:year/:title/"

# Navbar element's order configured with weight
[menu]
    
    [[menu.main]]
        identifier  = "screenshots"
        name        = "Screenshots"
        url         = "/screenshots/"
        weight      = 2
    
    [[menu.main]]
        identifier  = "videos"
        name        = "Videos"
        url         = "/videos/"
        weight      = 3

    [[menu.main]]
        identifier  = "docs"
        name        = "Documentation"
        url         = "https://docs.qtile.org"
        weight      = 4

    [[menu.main]]
        identifier  = "issues"
        name        = "Issues"
        url         = "https://github.com/qtile/qtile/issues/"
        weight      = 5
    
    [[menu.main]]
        identifier  = "github"
        name        = "GitHub"
        url         = "https://github.com/qtile/qtile/"
        weight      = 6

# Site wide information parameters which can be used in templates 
# using eg; {{ .Site.Params.qtileLogo }}
[params]    
    qtileLogo           = "/images/qtile-logo-white.webp"
    currentRelease      = "v0.23.0, Sept. 24, 2023"
